use_frameworks!

platform :ios, '8.0'

target 'UDCycleView_Example' do
  pod 'UDCycleView', :path => '../'

  target 'UDCycleView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
